### PR TITLE
Port to qt5

### PR DESCRIPTION
**Pull request by pierrewillenbrockdfki**
@planthaber This is supposed to land on a branch called "feature/qt5", but github does not allow to specify that in a pull request, so that branch would have to be created beforehand.

### CODE REVIEW

**Comment by planthaber** [comment]
I don't have access to dfki-planning @skasperski?

FYI: you can just click on the branch selector here on github, insert "feature/qt5" in to the search fieln and then klick on "create branch"

**Comment by skasperski** [comment]
@planthaber me neither

**Comment by 2maz** [comment]
@planthaber changed your membership to owner

**Comment by pierrewillenbrockdfki** [comment]
> FYI: you can just click on the branch selector here on github, insert "feature/qt5" in to the search fieln and then klick on "create branch"

I would have expected to be able to just push a new branch using git, but (see envire project) you have to do that through github, even when you can otherwise push just fine, it seems.

**Comment by planthaber** [comment]
Branch created.

Pierre is not a member of rock-planning so he cannot push branches directly. His the MR is from a fork.

**Comment by pierrewillenbrockdfki** [comment]
@planthaber this PR is now ready to be merged.

**Pull request merged**
